dist: xenial
language: python
python: 3.7
# command to install dependencies
install:
  - pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-16.04 wxPython==4.0.7
  - pip install -e .
  - pip install pytest
# command to run tests
script:
  - python -m pytest
deploy:
  on:
    branch: dev
    tags: true
  provider: pypi
  user: $pypi_user
  password: $pypi_password
