dist: trusty
language: python
python: 3.7
addons:
  apt:
    packages:
      # for wxPython:
      - python-wxgtk2.8
      - python-wxtools
      - wx2.8-doc
      - wx2.8-examples
      - wx2.8-headers
      - wx2.8-i18n
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - pipenv run python -m unittest discover -s wxviews -p *_tests.py
deploy:
  on:
    branch: dev
    tags: true
  provider: pypi
  user: $pypi_user
  password: $pypi_password
