dist: xenial
language: python
python: 3.7
# command to install dependencies
install:
  - sudo apt-get install -y python-wxgtk2.8
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - pipenv run python -m unittest discover -s wxviews -p *_tests.py
deploy:
  on:
    branch: dev
    tags: true
  provider: pypi
  user: $pypi_user
  password: $pypi_password
